# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

Без использования numpy

In [ ]:
def mult(a, b):
    result = None
    rows_a = len(a)
    cols_a = len(a[0])
    rows_b = len(b)
    cols_b = len(b[0])

    result = [[0 for row in range(cols_b)] for col in range(rows_a)]
    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                result[i][j] += a[i][k] * b[k][j]
            result[i][j] = round(result[i][j], 8)
            result[i][j] = np.round(result[i][j], 8)
    return result
print(mult(a, b))

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = None
    result = np.round(np.dot(a, b), 8)
    return result
print(np_mult(a, b))

In [142]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 552 ms, sys: 0 ns, total: 552 ms
Wall time: 554 ms


In [143]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.18 ms, sys: 761 µs, total: 2.95 ms
Wall time: 3.23 ms


In [144]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0.0

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [145]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.55106205 0.09031886 0.21530328] [0.9567355  0.65985449 0.87526449]


In [146]:
def scalar_product(a,b):
    s = 0
    s = sum(ai * bi for ai, bi in zip(a, b))
    return s
print(scalar_product(a,b))

0.7752652436614846


In [147]:
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s
print(np_scalar_product(a,b))

0.7752652436614846


In [148]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 18 µs, sys: 0 ns, total: 18 µs
Wall time: 19.6 µs
CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 38.9 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:**Методы NumPy оказываются эффективнее благодаря использованию оптимизированных операций на языке C, что делает его быстрым.Также Numpy позволяет выполнять векторизованные операции, обрабатывая данные для целых массивов, что делает вычисления более эффективными, чем обычные циклы в Python

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  main = np.diag(a)
  pob = np.diag(a[::-1])
  res_main = main[main % 2 == 0]
  res_pob = pob[pob % 2 == 0]
  res = sum(res_main) + sum(res_pob)
  return res
print(np_diag_2k(a))

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = None
    cumsum = np.cumsum(A)
    divisors = np.arange(1, len(A) + 1)
    result = cumsum / divisors
    return result
print(np_sec_av(A))

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
%time S2 = np_sec_av(A)

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [200]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    changes = np.where(np.diff(a) != 0)[0] + 1
    changes = np.r_[0, changes, a.size]
    counts = np.diff(changes)
    result = a[changes[:-1]]
    return result, counts
print(np_encode(X))

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))


In [205]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 139 µs, sys: 11 µs, total: 150 µs
Wall time: 155 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [261]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    result = None
    Y = np.copy(X)
    Y[1::2] = a
    Y[0::2] = Y[0::2] ** 3
    Z = np.flip(Y)
    result = np.concatenate((X, Z))
    result = np.flip(result)
    return result[::-1]
print(np_transformation(X))

[  1   3   5   7   9 729   1 125   1   1]


In [262]:

X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 170 µs, sys: 0 ns, total: 170 µs
Wall time: 129 µs
